### ISSUE TITLE
Framework support for PHP 7/Mongo Driver

### ISSUE THREAD

**Issue by Overrideveloper** [stigwue/iriki#1]
### Framework support for PHP7-Mongo Driver

Noticed that the framework throws the exception `Fatal error: Uncaught Error: Class 'MongoClient' not found` when running on/with PHP7.
A possible solution is to write new code supporting the PHP7's Mongo Driver.

**Comment by stigwue** [comment]
Yes, Iriki currently supports PHP 5. We should get around to providing PHP7 support.
